# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_auto_20181219_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cccount',
            old_name='password',
            new_name='passwor',
        ),
    ]
