# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_auto_20181219_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cccount',
            new_name='Account',
        ),
    ]
