# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_auto_20181219_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='permission',
            field=models.CharField(default='admin', max_length=5),
        ),
        migrations.AddField(
            model_name='account',
            name='regTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DB.Account', unique=True),
        ),
        migrations.AlterField(
            model_name='downloadtimes',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DB.Account', unique=True),
        ),
    ]
