# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_auto_20181219_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='DB.Account', unique=True),
        ),
    ]
