# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0009_auto_20181219_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDN_VIP_Account',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
