# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0010_csdn_vip_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdn_vip_account',
            name='left_times',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='csdn_vip_account',
            name='today_use_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='csdn_vip_account',
            name='today_use_times',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='DB.Account'),
        ),
        migrations.AlterField(
            model_name='downloadtimes',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DB.Account'),
        ),
    ]
