# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0011_auto_20181220_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Km',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField()),
                ('km', models.CharField(max_length=100)),
                ('benTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('out_trade_no', models.CharField(max_length=100)),
                ('trade_no', models.CharField(max_length=100)),
                ('rel', models.CharField(max_length=50)),
                ('stat', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
