# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0013_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbKm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('km', models.CharField(blank=True, max_length=100, null=True)),
                ('bentime', models.DateTimeField(blank=True, db_column='benTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
                ('out_trade_no', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rel', models.CharField(blank=True, max_length=50, null=True)),
                ('stat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DB_km',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Km',
        ),
    ]
