# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('free', models.IntegerField()),
                ('permission', models.CharField(max_length=5)),
                ('regtime', models.DateTimeField(db_column='regTime')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSDN_Vip_Account',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('left_times', models.IntegerField()),
                ('today_use_limit', models.IntegerField(blank=True, null=True)),
                ('today_use_times', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DATA.CSDN_Vip_Account')),
            ],
        ),
        migrations.CreateModel(
            name='Km',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('km', models.CharField(blank=True, max_length=100, null=True)),
                ('bentime', models.DateTimeField(blank=True, db_column='benTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
                ('out_trade_no', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rel', models.CharField(blank=True, max_length=50, null=True)),
                ('stat', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadTimes',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DATA.Account')),
                ('times', models.IntegerField()),
            ],
        ),
    ]
