# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DATA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtimes',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DATA.Account'),
        ),
    ]
