# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATA', '0002_auto_20181223_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='regtime',
            field=models.DateTimeField(auto_now=True, db_column='regTime'),
        ),
    ]
