# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATA', '0003_auto_20181223_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='km',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
